# -*- coding: utf-8 -*-
"""1. Data_Extraction_&_Enrichment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NjNk2aV_OFhSCtabDH9SX3BUGrKzPCAk
"""

from google.colab import drive
drive.mount('/content/drive')

"""# **Your Wallet Is a Fingerprint: Behavioral Biometrics in Financial Metadata**

## **Data Science 112 Final Project: Data Extraction & Enrichment**

### Elliot & Angelina

This project explores the IBM Credit Card Transactions Dataset (https://www.kaggle.com/datasets/ealtman2019/credit-card-transactions?resource=download&select=credit_card_transactions-ibm_v2.csv) to determine if a user's identity can be modeled as a "mathematical rhythm" rather than a static credential.


Research questions:
 1. Can consumers be grouped into behavioral profiles based on the rhythm, range, and variety of their spending activity?


In this file, we extract data from the raw transaction logs and enrich it with external Merchant Category (MCC) taxonomies and Geospatial APIs to form the dataset.

**1. Data Ingestion & Initial Cleaning**
"""

import pandas as pd
import numpy as np
#import pgeocode
import requests

np.random.seed(42) #so starts at 43

cols_needed = [
    'User', 'Card', 'Year', 'Month', 'Day', 'Time',
    'Amount', 'Use Chip', 'MCC', 'Zip'
]

df = pd.read_csv(
    '/content/drive/MyDrive/credit_card_transactions-ibm_v2.csv',
    usecols=cols_needed
)
df.head()

sampled_ids = np.random.choice(df['User'].unique(), size=500, replace=False)
df_500 = df[df['User'].isin(sampled_ids)].copy()

# Relabel users to 0...499
df_500['User'] = df_500.groupby('User').ngroup()

del df

df_500

"""**1. Web Scraping Merchant Metadata**"""

url = "https://raw.githubusercontent.com/greggles/mcc-codes/master/mcc_codes.json"

try:
    response = requests.get(url, timeout=10)
    response.raise_for_status()
    data = response.json()
    mcc_map = {int(item['mcc']): item['edited_description'] for item in data}
except Exception as e:
    print("MCC mapping download failed:", e)
    mcc_map = {}

df_500['MCC'] = pd.to_numeric(df_500['MCC'], errors='coerce')
df_500['MCC Category'] = df_500['MCC'].map(mcc_map).fillna('Other')

df_500[['MCC', 'MCC Category']].head()

broad_categories = {

    "Food & Dining": [
        "restaurant", "fast food", "cafe", "coffee", "bar", "pub", "pizza",
        "dining", "bakery", "catering", "food truck", "sandwich", "deli",
        "steakhouse", "buffet", "ice cream", "food service"
    ],

    "Groceries": [
        "grocery", "supermarket", "convenience", "food store", "market",
        "wholesale club", "warehouse club", "butcher", "produce", "farm",
        "food retailer"
    ],

    "Retail": [
        "department store", "clothing", "apparel", "shoe", "electronics",
        "jewelry", "watch", "home furnishing", "furniture", "hardware",
        "sporting goods", "toy", "gift", "book", "office supply",
        "computer", "camera", "music store", "record shop",
        "retail", "store", "merchandise"
    ],

    "Travel": [
        "airline", "air carrier", "airport", "hotel", "motel", "lodging",
        "resort", "travel agency", "tour", "cruise", "timeshare",
        "car rental", "vehicle rental"
    ],

    "Transport": [
        "gas", "fuel", "service station", "taxi", "ride", "transit",
        "railroad", "bus", "subway", "parking", "toll", "transport",
        "automotive", "auto service", "vehicle service"
    ],

    "Health": [
        "pharmacy", "drug", "medical", "hospital", "dentist",
        "physician", "clinic", "optical", "vision", "health",
        "chiropractor", "nursing", "laboratory"
    ],

    "Entertainment": [
        "theater", "cinema", "movie", "amusement", "theme park",
        "casino", "gaming", "sport", "bowling", "golf",
        "concert", "music venue", "club", "nightclub"
    ],

    "Financial": [
        "insurance", "financial", "broker", "investment",
        "bank", "credit", "loan", "mortgage", "securities",
        "atm", "money transfer"
    ],

    "Services": [
        "repair", "cleaning", "laundry", "photography",
        "consulting", "legal", "accounting", "tax",
        "security", "employment", "printing",
        "professional service", "business service"
    ],

    "Utilities": [
        "electric", "gas utility", "water", "telecommunication",
        "internet", "cable", "satellite", "utility", "energy",
        "telephone", "mobile"
    ],

    "Government & Education": [
        "government", "tax payment", "court", "municipal",
        "school", "college", "university", "education"
    ]
}

unique_categories = df_500['MCC Category'].dropna().unique()

category_map = {}

for cat in unique_categories:
    assigned = "Other"
    for group, keywords in broad_categories.items():
        if any(word.lower() in str(cat).lower() for word in keywords):
            assigned = group
            break
    category_map[cat] = assigned

df_500['Behavior_Category'] = df_500['MCC Category'].map(category_map).fillna("Other")

df_500['Behavior_Category'].value_counts()

"""**2.: REST API & Geospatial Enrichment**"""

df_500['Zip_clean'] = (
    df_500['Zip']
    .astype(str)
    .str.extract(r'(\d{1,5})')[0]
    .str.zfill(5)
)

df_500[['Zip', 'Zip_clean']].head()

pip install pgeocode

import pgeocode

nomi = pgeocode.Nominatim('us')

unique_zips = pd.Series(df_500['Zip_clean'].dropna().unique())
coords = nomi.query_postal_code(unique_zips.tolist())

zip_lookup = coords[['postal_code', 'latitude', 'longitude']].copy()
zip_lookup = zip_lookup.rename(columns={'postal_code': 'Zip_clean'})
zip_lookup['Zip_clean'] = zip_lookup['Zip_clean'].astype(str).str.zfill(5)
zip_lookup = zip_lookup.drop_duplicates(subset='Zip_clean')

df_500 = df_500.drop(columns=['latitude', 'longitude'], errors='ignore')

df_500 = df_500.merge(
    zip_lookup,
    on='Zip_clean',
    how='left'
)
df_500

"""online transactions have naan

**keep columns i want**
"""

df_clean = df_500[
    [
        'User',
        'Card',
        'Year',
        'Month',
        'Day',
        'Time',
        'Amount',
        'Use Chip',
        'MCC',
        'Behavior_Category',
        'Zip_clean',
        'latitude',
        'longitude'
    ]
].copy()

df_clean.head()

"""**Clean amount**"""

df_clean['Amount'] = (
    df_clean['Amount']
    .replace(r'[\$,]', '', regex=True)
    .astype(float)
)

df_clean['Amount'].head()

"""**date and time cleaning**"""

df_clean['DateTime'] = pd.to_datetime(
    df_clean[['Year','Month','Day']].astype(str).agg('-'.join, axis=1)
    + ' ' + df_clean['Time'],
    errors='coerce'
)

df_clean

df_clean.to_pickle('/content/drive/MyDrive/df_clean.pkl')

import os
os.path.exists('/content/drive/MyDrive/df_clean.pkl')