# -*- coding: utf-8 -*-
"""2. Exploratory_Data_Analysis_(EDA). ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fNqf4ok_ge43aMM8EdndA3ctyd9Mvyv-
"""

from google.colab import drive
drive.mount('/content/drive')

"""# **Your Wallet Is a Fingerprint: Behavioral Biometrics in Financial Metadata**

## **Data Science 112 Final Project: Exploratory Data Analysis:**

### Elliot & Angelina

This project explores the IBM Credit Card Transactions Dataset to determine if a user's identity can be modeled as a "mathematical rhythm" rather than a static credential.

Research question:

 1. How does the geographic range of transactions differ across consumers?
 2. How diverse are consumers’ spending categories?
 3. How does the rhythm of spending vary across consumers?
 4. Can machine learning distinguish between archetypes like the "Engaged Explorers" and the "Casual Locals" using only anonymized metadata?

In this file, we analyze each of the three behavioral metrics, then train a Random Forest Classifier model on 500 selected users in order to determine which feature of a transaction observation is the greatest determinant of a user's identity.

### **When, Where, What**

**The When**: Temporal Burstiness ($B$) measures the inter-event time ($\tau$), which is the time elapsed between one transaction and the next for a given consumer.

The Math: For each user, we calculate the Mean ($\mu_{\tau}$) and the Standard Deviation ($\sigma_{\tau}$) of the time gaps between consecutive transactions. Burstiness is computed on these inter-event times to capture the rhythm of spending behavior.

The Formula:
$$B = \frac{\sigma_{\tau} - \mu_{\tau}}{\sigma_{\tau} + \mu_{\tau}}$$

Verification: If $B = 1$, transactions occur in extreme bursts (many transactions in a short time followed by long inactivity). If $B = -1$, spending is perfectly regular (transactions occur at fixed intervals). If $B = 0$, spending follows a random pattern similar to a Poisson process.


---


**The Where**: Spatial Displacement ($R_g$)

The Baseline: Instead of assuming a fixed home location, we estimate a consumer’s **center of activity** by computing the mean latitude and longitude of all their in-person transactions. Online transactions are excluded from spatial calculations because they do not represent a physical location.

Calculation: Physical Departure For each transaction, we compute the Haversine distance ($d_i$) between the transaction location and the user’s center of activity. This measures how far each purchase occurs from the consumer’s typical spending location.

The Formula: Radius of Gyration
$$R_g = \sqrt{\frac{1}{N} \sum_{i=1}^{N} (d_i)^2}$$

The Log-Transformation (Normalization): Because human mobility follows a heavy-tailed distribution (most consumers spend locally while a few travel widely), we apply a logarithmic transformation to stabilize the range of values:

$$\text{Spatial\_Range} = \ln(1 + R_g)$$


---


**The What:** Categorical Entropy ($H$)

This metric uses Information Theory to measure the diversity of merchant categories in a consumer’s spending behavior.

The Input: The probability ($P$) of transactions occurring in each behavioral category (derived from Merchant Category Codes). For example, a user might spend 50% in groceries, 30% in transportation, and 20% in dining.

The Formula:
$$H = -\sum_{i=1}^{n} P(x_i)\log_2 P(x_i)$$

Normalization: To make entropy comparable across users, the value is normalized by the maximum possible entropy given the number of spending categories:

$$H_{norm} = \frac{H}{\log_2(K)}$$

where $K$ is the number of behavioral categories.

Verification: A user with **low entropy** is a "Specialist" (spending concentrated in a few categories), while a user with **high entropy** is a "Generalist" (spending distributed across many categories).
"""

import pandas as pd
import numpy as np
import requests
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

df_clean = pd.read_pickle('/content/drive/MyDrive/df_clean.pkl')

df_clean

"""Zip_clean:
Standardized ZIP code corresponding to the merchant location where the transaction occurred. ZIP codes were converted into latitude and longitude coordinates to enable spatial analysis of consumer spending mobility.

# **1. The When: Temporal Burstiness ($B$)**
"""

import pandas as pd
import numpy as np

# Work on a copy so original df_clean is unchanged
df_temporal = df_clean.copy()

# 1. Make sure DateTime is datetime
df_temporal['DateTime'] = pd.to_datetime(df_temporal['DateTime'], errors='coerce')

# Remove invalid timestamps
df_temporal = df_temporal.dropna(subset=['DateTime']).copy()

# 2. Keep only 2009–2019
df_temporal['Year_Val'] = df_temporal['DateTime'].dt.year
df_temporal = df_temporal[
    (df_temporal['Year_Val'] >= 2009) &
    (df_temporal['Year_Val'] <= 2019)
].copy()

# 3. Sort by user and time
df_temporal = df_temporal.sort_values(['User', 'DateTime'])

# 4. Compute inter-event time in hours within each user-year
df_temporal['diff'] = (
    df_temporal
    .groupby(['User', 'Year_Val'])['DateTime']
    .diff()
    .dt.total_seconds() / 3600
)

# 5. Burstiness function
def calculate_burstiness(x):
    x = x.dropna()

    # Need enough inter-event gaps for a stable estimate
    if len(x) < 10:
        return np.nan

    mu = x.mean()
    sigma = x.std(ddof=0)

    if (sigma + mu) == 0:
        return np.nan

    return (sigma - mu) / (sigma + mu)

# 6. Yearly burstiness per user
temporal_stats = (
    df_temporal
    .groupby(['User', 'Year_Val'])['diff']
    .apply(calculate_burstiness)
    .reset_index(name='Temporal_B_year')
)

# Optional: drop user-years that returned NaN
temporal_stats = temporal_stats.dropna(subset=['Temporal_B_year']).copy()

# 7. Final user-level burstiness = average across years
burstiness_user = (
    temporal_stats
    .groupby('User', as_index=False)['Temporal_B_year']
    .mean()
    .rename(columns={'Temporal_B_year': 'Temporal_B'})
)

burstiness_user.head()

"""# **Block 2: The Where — Spatial Displacement ($R_{g}$)**"""

df_spatial = df_clean.copy()
df_spatial

import numpy as np
import pandas as pd

# --------------------------------------------------
# CLEAN UP ANY OLD ANCHOR COLUMNS
# --------------------------------------------------
df_spatial = df_spatial.drop(
    columns=['Anchor_Zip', 'Anchor_Latitude', 'Anchor_Longitude'],
    errors='ignore'
)

# --------------------------------------------------
# HAVERSINE DISTANCE FUNCTION
# --------------------------------------------------
def haversine_dist(lat1, lon1, lat2, lon2):
    R = 6371.0

    phi1 = np.radians(lat1)
    phi2 = np.radians(lat2)

    dphi = np.radians(lat2 - lat1)
    dlambda = np.radians(lon2 - lon1)

    a = np.sin(dphi / 2) ** 2 + np.cos(phi1) * np.cos(phi2) * np.sin(dlambda / 2) ** 2

    return 2 * R * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

# --------------------------------------------------
# 1. BUILD USER ANCHORS FROM MOST FREQUENT PHYSICAL ZIP
# --------------------------------------------------
physical_tx = df_spatial.dropna(subset=['latitude', 'longitude', 'Zip_clean'])

anchor_df = (
    physical_tx
    .groupby(['User', 'Zip_clean'])
    .agg(
        tx_count=('User', 'size'),
        Anchor_Latitude=('latitude', 'first'),
        Anchor_Longitude=('longitude', 'first'),
    )
    .reset_index()
    .sort_values(['User', 'tx_count'], ascending=[True, False])
    .drop_duplicates(subset='User')
    .rename(columns={'Zip_clean': 'Anchor_Zip'})
)

print(f"Users with a physical anchor: {anchor_df['User'].nunique()}")

all_users = df_spatial['User'].nunique()
anchored_users = anchor_df['User'].nunique()
print(f"{all_users - anchored_users} users dropped (no physical transactions)")

# --------------------------------------------------
# 2. MERGE ANCHORS BACK INTO df_spatial
# --------------------------------------------------
df_spatial = df_spatial.merge(
    anchor_df[['User', 'Anchor_Zip', 'Anchor_Latitude', 'Anchor_Longitude']],
    on='User',
    how='left'
)

# Quick check
print(df_spatial[['User', 'Zip_clean', 'Anchor_Zip', 'Anchor_Latitude', 'Anchor_Longitude']].head())

# --------------------------------------------------
# 3. COMPUTE SPATIAL RANGE PER USER
# --------------------------------------------------
results = []

for user_id, group in df_spatial.groupby('User'):

    if len(group) < 2:
        continue

    anchor_lat = group['Anchor_Latitude'].iloc[0]
    anchor_lon = group['Anchor_Longitude'].iloc[0]

    if pd.isna(anchor_lat) or pd.isna(anchor_lon):
        continue

    # Only compute distances for physically located transactions
    phys = group.dropna(subset=['latitude', 'longitude'])

    if len(phys) < 2:
        continue

    distances = haversine_dist(
        phys['latitude'].values,
        phys['longitude'].values,
        anchor_lat,
        anchor_lon
    )

    # Remove extreme outliers
    if len(distances) >= 5:
        cutoff = np.percentile(distances, 99)
        distances = distances[distances <= cutoff]

    if len(distances) < 2:
        continue

    rg = np.sqrt(np.mean(distances ** 2))

    results.append({
        'User': user_id,
        'Year': '2009-2019',
        'Rg_km': rg,
        'Spatial_Log': np.log1p(rg),
        'Transaction_Count': len(distances)
    })

spatial_results = pd.DataFrame(results)

# --------------------------------------------------
# 4. USER-LEVEL SUMMARY
# --------------------------------------------------
rg_user = spatial_results[['User', 'Rg_km', 'Spatial_Log', 'Transaction_Count']].copy()

print("Spatial results shape:", spatial_results.shape)
print("User summary shape:", rg_user.shape)
print("Unique users in rg_user:", rg_user['User'].nunique())

rg_user

"""# **Block 3: The What — Categorical Entropy ($H$)**"""

import numpy as np
import pandas as pd

df_entropy = df_clean.copy()

print(df_entropy.shape)
df_entropy.head()

df_entropy['DateTime'] = pd.to_datetime(df_entropy['DateTime'], errors='coerce')

df_entropy = df_entropy.dropna(subset=['DateTime']).copy()

df_entropy = df_entropy[
    (df_entropy['DateTime'].dt.year >= 2009) &
    (df_entropy['DateTime'].dt.year <= 2019)
].copy()

df_entropy = df_entropy.dropna(subset=['Behavior_Category']).copy()

user_tx_counts = df_entropy.groupby('User').size()

valid_users = user_tx_counts[user_tx_counts >= 10].index

df_entropy = df_entropy[df_entropy['User'].isin(valid_users)].copy()

print(df_entropy['User'].nunique())

user_cat_counts = (
    df_entropy
    .groupby(['User', 'Behavior_Category'])
    .size()
    .reset_index(name='tx_count')
)

user_cat_counts.head()

user_totals = (
    df_entropy
    .groupby('User')
    .size()
    .reset_index(name='total_tx')
)

user_totals.head()

entropy_df = user_cat_counts.merge(user_totals, on='User', how='left')

entropy_df['p'] = entropy_df['tx_count'] / entropy_df['total_tx']

entropy_df.head()

entropy_df['h_i'] = -entropy_df['p'] * np.log2(entropy_df['p'])

entropy_df.head()

entropy_stats = (
    entropy_df
    .groupby('User', as_index=False)['h_i']
    .sum()
    .rename(columns={'h_i': 'Diversity_H'})
)

entropy_stats.head()

K = df_entropy['Behavior_Category'].nunique()

entropy_stats['Diversity_H_norm'] = entropy_stats['Diversity_H'] / np.log2(K)

entropy_stats.head()

"""# **Master consumer behaviors**"""

consumer_behavior_features = (
    burstiness_user[['User', 'Temporal_B']]
    .merge(rg_user[['User', 'Spatial_Log']], on='User', how='inner')
    .merge(entropy_stats[['User', 'Diversity_H_norm']], on='User', how='inner')
    .merge(anchor_df[['User', 'Anchor_Zip', 'Anchor_Latitude', 'Anchor_Longitude']], on='User', how='left')
    .rename(columns={
        'Temporal_B': 'Temporal_Burstiness',
        'Spatial_Log': 'Spatial_Range',
        'Diversity_H_norm': 'Categorical_Variety'
    })
)
consumer_behavior_features

consumer_behavior_features.to_pickle('/content/drive/MyDrive/consumer_behavior_features.pkl')

"""**Temporal_Burstiness** (Rhythm)
Measures how transactions are distributed over time. Values near 0 indicate steady or random spending patterns, positive values indicate bursts of spending activity, and negative values suggest highly regular purchasing behavior.

**Spatial_Range** (Range)
Represents the geographic dispersion of a consumer’s transactions using the log-transformed radius of gyration. Higher values indicate that purchases occur across a broader geographic area, while lower values indicate spending concentrated within a local region.

**Categorical_Variety** (Variety)
A normalized entropy measure of merchant categories used by a consumer. Values closer to 1 indicate diverse spending across many categories, while lower values indicate more concentrated spending in fewer categories.

# **Graphs**
"""

from scipy.stats import rankdata

# -----------------------------
# NORMALIZE THE THREE METRICS
# -----------------------------
normalized_df = consumer_behavior_features.copy()

normalized_df['Burstiness_norm'] = (
    rankdata(normalized_df['Temporal_Burstiness']) - 1
) / (len(normalized_df) - 1)

normalized_df['Spatial_norm'] = (
    rankdata(normalized_df['Spatial_Range']) - 1
) / (len(normalized_df) - 1)

normalized_df['Variety_norm'] = (
    rankdata(normalized_df['Categorical_Variety']) - 1
) / (len(normalized_df) - 1)

print(normalized_df[['Burstiness_norm', 'Spatial_norm', 'Variety_norm']].describe())

import numpy as np

for metric in ['Burstiness_norm', 'Spatial_norm', 'Variety_norm']:
    counts, bins = np.histogram(normalized_df[metric].dropna(), bins=40, range=(0,1))
    pct = counts / len(normalized_df) * 100
    print(f"{metric}: max bin = {pct.max().round(1)}%")

# -----------------------------
# NORMALIZE THE THREE METRICS
# -----------------------------
normalized_df = consumer_behavior_features.copy()

normalized_df['Burstiness_norm'] = (
    (normalized_df['Temporal_Burstiness'] - normalized_df['Temporal_Burstiness'].min()) /
    (normalized_df['Temporal_Burstiness'].max() - normalized_df['Temporal_Burstiness'].min())
)

normalized_df['Spatial_norm'] = (
    (normalized_df['Spatial_Range'] - normalized_df['Spatial_Range'].min()) /
    (normalized_df['Spatial_Range'].max() - normalized_df['Spatial_Range'].min())
)

normalized_df['Variety_norm'] = (
    (normalized_df['Categorical_Variety'] - normalized_df['Categorical_Variety'].min()) /
    (normalized_df['Categorical_Variety'].max() - normalized_df['Categorical_Variety'].min())
)

print(normalized_df[['Burstiness_norm', 'Spatial_norm', 'Variety_norm']].describe())

from sklearn.cluster import KMeans

X = normalized_df[['Burstiness_norm', 'Spatial_norm', 'Variety_norm']].dropna()

km = KMeans(n_clusters=4, random_state=42, n_init=10)
normalized_df = normalized_df.copy()
normalized_df.loc[X.index, 'Cluster'] = km.fit_predict(X)
normalized_df['Cluster'] = normalized_df['Cluster'].astype('Int64')

import plotly.graph_objects as go

cluster_names = {
    0: "Engaged Explorers",
    1: "Casual Locals",
    2: "Routine Specialists",
    3: "Erratic Minimalists"
}

colors = {
    0: '#E763FA',
    1: '#FF6B35',
    2: '#00B4D8',
    3: '#FFD166'
}

normalized_df['Cluster_Name'] = normalized_df['Cluster'].map(cluster_names)

fig_scatter = go.Figure()

for cluster_id, name in cluster_names.items():
    subset = normalized_df[normalized_df['Cluster'] == cluster_id]
    fig_scatter.add_trace(go.Scatter(
        x=subset['Burstiness_norm'],
        y=subset['Variety_norm'],
        mode='markers',
        name=name,
        marker=dict(color=colors[cluster_id], size=7, opacity=0.7,
                    line=dict(color='white', width=0.5))
    ))

fig_scatter.update_layout(
    title=dict(
        text="Spending Rhythm vs. Category Diversity by Cluster",
        x=0.5, xanchor='center',
        font=dict(family="Times New Roman", size=23, color="black")
    ),
    xaxis=dict(
        title="Spending Rhythm Score (0 = steady, 1 = bursty)",
        range=[0, 1], linecolor='black', mirror=True, gridcolor='#eeeeee'
    ),
    yaxis=dict(
        title="Category Diversity Score (0 = few, 1 = many)",
        range=[0, 1], linecolor='black', mirror=True, gridcolor='#eeeeee'
    ),
    paper_bgcolor='white',
    plot_bgcolor='#F0F8FF',
    font=dict(family="Times New Roman", size=13),
    legend=dict(orientation='h', y=-0.2),
    height=500, width=700,
    margin=dict(t=80, b=100)
)

fig_scatter.show()

from sklearn.metrics import silhouette_score

X = normalized_df[['Burstiness_norm', 'Spatial_norm', 'Variety_norm']].dropna()
score = silhouette_score(X, normalized_df.loc[X.index, 'Cluster'])
print(f"Silhouette Score: {score:.3f}")

import plotly.subplots as sp
import plotly.graph_objects as go

fig = sp.make_subplots(
    rows=1,
    cols=3,
    subplot_titles=[
        "Spending Rhythm (Temporal Burstiness)",
        "Geographic Reach (Radius of Gyration)",
        "Category Diversity (Shannon Entropy)"
    ],
    horizontal_spacing=0.10
)

fig.add_trace(
    go.Histogram(
        x=normalized_df['Burstiness_norm'],
        nbinsx=40,
        marker=dict(color='#636EFA', line=dict(color='white', width=1)),
        opacity=0.9
    ),
    row=1, col=1
)

fig.add_trace(
    go.Histogram(
        x=normalized_df['Spatial_norm'],
        nbinsx=40,
        marker=dict(color='#EF553B', line=dict(color='white', width=1)),
        opacity=0.9
    ),
    row=1, col=2
)

fig.add_trace(
    go.Histogram(
        x=normalized_df['Variety_norm'],
        nbinsx=40,
        marker=dict(color='#00CC96', line=dict(color='white', width=1)),
        opacity=0.9
    ),
    row=1, col=3
)

fig.update_layout(
    height=500,
    width=1150,
    title=dict(
        text="Distribution of Consumer Spending Behavior (2009–2019)",
        x=0.5,
        xanchor='center',
        font=dict(family="Times New Roman", size=23, color="black")
    ),
    paper_bgcolor='white',
    plot_bgcolor='#F0F8FF',
    font=dict(family="Times New Roman", size=15, color="black"),
    showlegend=False,
    margin=dict(t=110, l=80, r=30, b=100)
)

fig.update_xaxes(
    title_text="Burstiness Score (0 = steady, 1 = bursty)",
    range=[0, 1], linecolor='black', mirror=True, gridcolor='white',
    row=1, col=1
)

fig.update_xaxes(
    title_text="Geographic Reach Score (0 = local, 1 = wide)",
    range=[0, 1], linecolor='black', mirror=True, gridcolor='white',
    row=1, col=2
)

fig.update_xaxes(
    title_text="Diversity Score (0 = few categories, 1 = many)",
    range=[0, 1], linecolor='black', mirror=True, gridcolor='white',
    row=1, col=3
)

for col in [1, 2, 3]:
    fig.update_yaxes(
        title_text="Number of Consumers" if col == 1 else "",
        range=[0, 130],
        linecolor='black', mirror=True, gridcolor='white',
        row=1, col=col
    )

fig.show()

import plotly.graph_objects as go

cluster_order = ['Engaged Explorers', 'Casual Locals', 'Routine Specialists', 'Erratic Minimalists']
row_colors = ['#F9E0FF', '#FFE8DC', '#D6F4FB', '#FFF8DC']

profile = (
    normalized_df
    .groupby('Cluster_Name')[['Burstiness_norm', 'Spatial_norm', 'Variety_norm']]
    .mean()
    .round(2)
    .loc[cluster_order]
    .reset_index()
)

counts = normalized_df['Cluster_Name'].value_counts()
profile['% of Users'] = (counts[cluster_order].values / 401 * 100).round(1).astype(str) + '%'

fig = go.Figure(go.Table(
    header=dict(
        values=['<b>Segment</b>', '<b>Spending Rhythm</b>', '<b>Geographic Reach</b>', '<b>Category Diversity</b>', '<b>% of Users</b>'],
        fill_color='#2c3e7a',
        font=dict(color='white', size=13, family="Times New Roman"),
        align='center',
        height=40
    ),
    cells=dict(
        values=[
            profile['Cluster_Name'],
            profile['Burstiness_norm'],
            profile['Spatial_norm'],
            profile['Variety_norm'],
            profile['% of Users']
        ],
        fill_color=[row_colors],
        font=dict(size=13, family="Times New Roman"),
        align='center',
        height=35
    )
))

fig.update_layout(
    title=dict(
        text="Consumer Segment Profiles",
        x=0.5, xanchor='center',
        font=dict(family="Times New Roman", size=23, color="black")
    ),
    height=320, width=780,
    margin=dict(t=80, b=20)
)

fig.show()

from sklearn.ensemble import RandomForestClassifier
import plotly.graph_objects as go

X = normalized_df[['Burstiness_norm', 'Spatial_norm', 'Variety_norm']].dropna()
y = normalized_df.loc[X.index, 'Cluster']

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X, y)

importances = rf.feature_importances_
feature_names = ['Spending Rhythm', 'Geographic Reach', 'Category Diversity']

fig = go.Figure(go.Bar(
    x=feature_names,
    y=importances,
    marker=dict(
        color=['#636EFA', '#EF553B', '#00CC96'],
        line=dict(color='white', width=1)
    ),
    text=[f"{v:.3f}" for v in importances],
    textposition='outside'
))

fig.update_layout(
    title=dict(
        text="Feature Importance for Consumer Segment Classification",
        x=0.5, xanchor='center',
        font=dict(family="Times New Roman", size=23, color="black")
    ),
    xaxis=dict(title="Behavioral Dimension", linecolor='black', mirror=True),
    yaxis=dict(title="Importance Score", linecolor='black', mirror=True,
               gridcolor='#eeeeee', range=[0, 0.6]),
    paper_bgcolor='white',
    plot_bgcolor='#F0F8FF',
    font=dict(family="Times New Roman", size=13),
    showlegend=False,
    height=400, width=600,
    margin=dict(t=80, b=80)
)

fig.show()

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# -----------------------------
# FEATURES FOR CLUSTERING
# -----------------------------
X = normalized_df[['Burstiness_norm', 'Spatial_norm', 'Variety_norm']].dropna()

# -----------------------------
# ELBOW PLOT TO PICK K
# -----------------------------
inertias = []
K_range = range(2, 10)

for k in K_range:
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X)
    inertias.append(km.inertia_)

plt.figure(figsize=(7, 4))
plt.plot(K_range, inertias, marker='o', color='steelblue')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Inertia')
plt.title('Elbow Plot — Choosing K')
plt.tight_layout()
plt.show()